version: '3.4'

services:
  healthChecker:
    image: ${DOCKER_REGISTRY-}healthchecker
    build:
      context: .
      dockerfile: HealthChecker/Dockerfile
    container_name: healthChecker-container
    env_file:
      - .env
